# Generated by Django 2.2.10 on 2020-02-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.CharField(max_length=200, unique=True)),
                ('container_class', models.CharField(max_length=200)),
                ('title_class', models.CharField(max_length=200)),
                ('tag_title', models.CharField(blank=True, max_length=200)),
                ('published_class', models.CharField(max_length=200)),
            ],
        ),
    ]
